# 数据合并(pd.concat)

In [ ]:
# 表示相同字段的数据进行首尾连接

In [1]:
import numpy as np
import pandas as pd

In [3]:
# 1. Numpy里的 concatenate
arr1 = np.random.randint(0, 10, (3, 4))
arr2 = np.random.randint(0, 10, (3, 4))

print(arr1)
print(arr2)
print("-" * 10)
# 默认轴方向是列，两个数组列部分首尾连接(6 * 3)
#print(np.concatenate([arr1, arr2]))
# axis 的轴方向是行，那么就是两个数的行部分首尾链接 (3 * 6)
print(np.concatenate([arr1, arr2], axis=1))

[[1 6 9 2]
 [3 0 1 1]
 [3 6 0 5]]
[[1 8 6 5]
 [9 5 4 3]
 [9 6 8 6]]
----------
[[1 6 9 2 1 8 6 5]
 [3 0 1 1 9 5 4 3]
 [3 6 0 5 9 6 8 6]]


In [ ]:
# 2. pandas 里的 concat

In [15]:
# 2.1 index 没有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(0,5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(5,9))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(9,12))

print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
print("-" * 10)
# 默认是按列进行连接，默认外连接
print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))

# axis = 1 按行连接，默认外连接
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1))

# 默认"outer"是外连接，join = "inner" 表示内连接（数据是交集）
# 如果没有交集的数据，则去除NaN所在的行/列
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1, join="inner"))

# print(pd.concat([ser_obj1, ser_obj2, ser_obj3], join="inner"))

0    4
1    4
2    5
3    3
4    0
dtype: int32
5    5
6    2
7    5
8    0
dtype: int32
9     7
10    6
11    1
dtype: int32
----------
0     4
1     4
2     5
3     3
4     0
5     5
6     2
7     5
8     0
9     7
10    6
11    1
dtype: int32


In [17]:
# 2.2 index 有重复的情况
ser_obj1 = pd.Series(np.random.randint(0, 10, 5), index=range(5))
ser_obj2 = pd.Series(np.random.randint(0, 10, 4), index=range(4))
ser_obj3 = pd.Series(np.random.randint(0, 10, 3), index=range(3))
print(ser_obj1)
print(ser_obj2)
print(ser_obj3)
print("-" * 10)
# 默认是按列进行连接，默认外连接
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3]))

# axis = 1 按行连接，默认外连接
#print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1))

# 默认"outer"是外连接，join = "inner" 表示内连接（数据是交集）
# 如果没有交集的数据，则去除NaN所在的行/列
print(pd.concat([ser_obj1, ser_obj2, ser_obj3], axis = 1, join="inner"))

# print(pd.concat([ser_obj1, ser_obj2, ser_obj3], join="inner"))

0    1
1    7
2    1
3    6
4    9
dtype: int32
0    5
1    0
2    3
3    0
dtype: int32
0    9
1    3
2    1
dtype: int32
----------
   0  1  2
0  1  5  9
1  7  0  3
2  1  3  1


In [18]:
## DataFrame 
df_obj1 = pd.DataFrame(np.random.randint(0, 10, (3, 2)), index=['a', 'b', 'c'],
                       columns=['A', 'B'])
df_obj2 = pd.DataFrame(np.random.randint(0, 10, (2, 2)), index=['a', 'b'],
                       columns=['C', 'D'])
print(df_obj1)
print(df_obj2)

   A  B
a  5  7
b  4  0
c  3  7
   C  D
a  0  9
b  2  9


In [21]:
#　默认是按行连接
#print(pd.concat([df_obj1, df_obj2]))
# 指定轴方向，通知按内连接(NaN所在的行/列将被去除)
print(pd.concat([df_obj1, df_obj2], axis = 1, join= "inner"))

   A  B  C  D
a  5  7  0  9
b  4  0  2  9
