## DataFrame 数据结构

In [1]:
import pandas as pd
import numpy as np

#### 1. 通过 ndarray构建DataFrame对象

In [2]:
arr_obj = np.random.rand(3, 4)
print(arr_obj)

[[ 0.63142018  0.40399522  0.44070245  0.58114319]
 [ 0.82655924  0.5716437   0.20031657  0.20645792]
 [ 0.42643845  0.65572268  0.11973222  0.95861301]]


In [4]:
df_obj = pd.DataFrame(arr_obj)
print(df_obj)
print(df_obj.head(2))

          0         1         2         3
0  0.631420  0.403995  0.440702  0.581143
1  0.826559  0.571644  0.200317  0.206458
2  0.426438  0.655723  0.119732  0.958613
          0         1         2         3
0  0.631420  0.403995  0.440702  0.581143
1  0.826559  0.571644  0.200317  0.206458


#### 2. 通过 dict 构建DataFrame对戏那个

In [17]:
dic = {
    "A" : 1,
    "B" : pd.Timestamp("20170426"),
    "C" : pd.Series(range(10, 14), dtype = "float64"),
    "D" : ["Python", "Java", "C++", "C"],
    "E" : np.array([3] * 4, dtype="int32"),
    "F" : "ITCast"
}

In [18]:
df_obj2 = pd.DataFrame(dic)
print(df_obj2)

   A          B     C       D  E       F
0  1 2017-04-26  10.0  Python  3  ITCast
1  1 2017-04-26  11.0    Java  3  ITCast
2  1 2017-04-26  12.0     C++  3  ITCast
3  1 2017-04-26  13.0       C  3  ITCast


In [27]:
# 在DataFrame对象里找到指定的元素，先找列，再找行
print(df_obj2['D'][2])
print(df_obj2.D[2])

C++
C++


In [29]:
# 新增加一列的数据，数据可以是和DataFrame对象的其他列运算后的数据
df_obj2["G"] = df_obj2["C"] + 10
print(df_obj2)

   A          B     C       D  E       F     G
0  1 2017-04-26  10.0  Python  3  ITCast  20.0
1  1 2017-04-26  11.0    Java  3  ITCast  21.0
2  1 2017-04-26  12.0     C++  3  ITCast  22.0
3  1 2017-04-26  13.0       C  3  ITCast  23.0


In [32]:
# 通过del方法，指定删除一列的数据
del(df_obj2['E'])
print(df_obj2)

   A          B     C       D       F     G
0  1 2017-04-26  10.0  Python  ITCast  20.0
1  1 2017-04-26  11.0    Java  ITCast  21.0
2  1 2017-04-26  12.0     C++  ITCast  22.0
3  1 2017-04-26  13.0       C  ITCast  23.0
